name: "Terraform Output Fetcher"
description: "Fetch outputs from a terraform workspace"
inputs:
  host:
    description: "host for self-hosted terraform cloud"
    required: true
    default: "app.terraform.io"
  organization:
    description: "organization on terraform cloud"
    required: true
  workspace:
    description: "workspace on terraform cloud"
    required: true
  token:
    description: "team token for terraform cloud"
    required: true
outputs:
  outputs:
    description: "The outputs of the terraform stack"
runs:
  using: "node16"
  main: "dist/index.js"
